### ISSUE TITLE
Line-Height of button unexist in imaged m-wrap

### ISSUE THREAD

**Issue by Bellegar** [ampier-io/ampier-framework#1]
If m-wrap contains background-image, produced m-button HTML code excludes line-height style attribute, so botton is not fully clickable.
It is perfectly seen on default template on https://ampier.io/playground/view/12556
Button over backgrounded m-wrap is not fully clickable, top and bottom of button is not clickable.

![image](https://github.com/ampier-io/ampier-framework/assets/8396703/0a6f3557-976c-4139-b067-7c67bc55b496)

If i manually set css style with line-height, button becames whole clickable.

That bug is producing in web playground's internal HTML generator.

**Comment by pixcraft-io** [comment]
Thank you for the feedback. Initially, it was done this way to avoid display issues in Outlook (which has problems with aligning text with line height). We addressed this problem by providing a separate variation for Outlook and all other email clients.
