### ISSUE TITLE
Combine with components from amp.dev

### ISSUE THREAD

**Issue by VadimZo** [ampier-io/ampier-framework#3]
How can I add components from amp.dev for email? When I add script with import, for example <script async custom-element=‘amp-timeago’ src=‘https://cdn.ampproject.org/v0/amp-timeago-0.1.js’></script> it is not applied. As workaround I could add it after download like amp, but I'd like to see it in playground

**Comment by VadimZo** [comment]
as workaround I could add it after download, but I'd like to see it in playground

**Comment by pixcraft-io** [comment]
We have add timeago component in TJML: https://github.com/pixcraft-io/TJML-framework/wiki#module_m-timeago
